name: Build Artifacts

on: 
  push:
    branches:
      - master # Triggers the workflow on any push to the master branch
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pdflatex cv_cem_philipp_freimoser.tex
      
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: cv
          path: cv_cem_philipp_freimoser.pdf # Specify the file path to the generated PDF